id: P006772
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:22:08.568096
source_metadata:
  id: bdr:W8LS17501
  title: གསུང་འབུམ། དགེ་བཤེས་ར་ལྡིར།
  author: ''
  volumes:
    8bc4b7564716406bbf92f092dddb3126:
      image_group_id: I8LS17515
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
    8fdb11681dfb4508a4ca747f456e7669:
      image_group_id: I8LS17516
      title: ''
      volume_number: 2
      total_pages: 80
      base_file: v002.txt
    99e47432cef247cf9d73a718dfb9b257:
      image_group_id: I8LS17517
      title: ''
      volume_number: 3
      total_pages: 110
      base_file: v003.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
