id: I4719784F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:36:11+00:00'
last_modified: '2022-06-08T06:45:07.460306+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17501
  title: གསུང་འབུམ། དགེ་བཤེས་ར་ལྡིར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7C3A:
      image_group_id: I8LS17515
      title: ''
      total_pages: 90
      order: 1
      base_file: 7C3A.txt
    A869:
      image_group_id: I8LS17516
      title: ''
      total_pages: 80
      order: 2
      base_file: A869.txt
    6F1F:
      image_group_id: I8LS17517
      title: ''
      total_pages: 110
      order: 3
      base_file: 6F1F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
