id: I4719784F
legacy_id: P006772
ocr_import_info:
  bdrc_scan_id: W8LS17501
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T18:35:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:54:25.472709+00:00'
last_modified: 2022-09-04 11:54:37.055306
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17501
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17501
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དགེ་བཤེས་ར་ལྡིར།
statistics:
  ocr_word_mean_confidence_index: 0.6281756911714695
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I8LS17516:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17516
      total_pages: 80
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I8LS17516.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6877931877345281
    legacy_id: v002
  I8LS17517:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17517
      total_pages: 110
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I8LS17517.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5855045761229369
    legacy_id: v003
  I8LS17515:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17515
      total_pages: 90
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17515.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6460092727349973
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
